version: '3.8'

services:
  
  django: 
    #restart: always
    build: 
      context: .
      dockerfile: ./Dockerfile
    volumes: 
      - "./:/docker_EGL/"
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports: 
      - "8000:8000"
    
    depends_on: 
      - db
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'EGL'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - "3306:3306" 
